### ISSUE TITLE
new release? python3 compat?

### ISSUE THREAD

**Issue by rimas-kudelis** [ispell-lt/ispell-lt#22]
Original Launchpad bug 1856108: https://bugs.launchpad.net/ispell-lt/+bug/1856108
Reported by: xnox (Dimitri John Ledkov).

new release? python3 compat?

ispell-lt in debian is at very old 1.2.1 version from 2008.

It has been orphaned and is about to be removed from both Debian and Ubuntu due to python2 usage.

Is current lp:ispell-lt python3 compatible?
Is there a new release that could be packaged and shipped?

Otherwise all users of Debian, Ubuntu and derivatives will be without ispell-lt.

**Comment by rimas-kudelis** [comment]
[ LP comment 1 by: Rimas Kudelis, on 2020-03-16 20:22:52.165920+00:00 ]

There was a newer release, v1.3.0 seven years ago, but there have been almost 30 new commits since then. I suppose the time has long since come for us to tag a new release. Would Debian update its package then?

**Comment by rimas-kudelis** [comment]
[ LP comment 2 by: Laimonas Vėbra, on 2020-03-16 21:58:10.955919+00:00 ]

ispell-lt is python3 compatible (tested with pythons from 2.3 to 3.6).

**Comment by xnox** [comment]
Please tag master as v1.3.1 or v1.4 such that i can download the tarball of the current master for packaging.

**Comment by xnox** [comment]
I'm trying to build master, but that fails to build aspell portions for me. See build log at https://github.com/ispell-lt/ispell-lt/pull/24

**Comment by rimas-kudelis** [comment]
ispell-lt v.1.3.2 has been released yesterday. I believe this bus can be closed?
