### ISSUE TITLE
Spellcheck neveikia LibreOffice 6.4.3.2

### ISSUE THREAD

**Issue by lifebarier** [ispell-lt/ispell-lt#25]
Operacine - linux manjaro.
Spellcheckas is https://extensions.libreoffice.org/extensions/lithuanian-spellcheck-and-hyphenation-dictionaries/1.3 neveikia.
1.3.1 versija is https://bugs.launchpad.net/ispell-lt/+bug/1157478 veikia.

Kodel nuo 2013-03-19 sita problema nera pataisyta? Ar cia man vienam neveikia?

**Comment by lifebarier** [comment]
@alga is this dead?

**Comment by rimas-kudelis** [comment]
Neaišku, kas atsakingas už žodyno įkėlimą į „Libreoffice“ platformą. Tikriausiai kažkada įkėliau aš, bet panašu, kad nebeturiu ten jokių prisijungimų.

Naujausią plėtinio versiją šiuo metu galima parsisiųsti iš https://github.com/ispell-lt/ispell-lt/releases/tag/rel-1.3.2. Tačiau: tie failai generuojami automatiškai, todėl jei kažkas pasikeitė „LibreOffice“ pusėje, tai gali būti, kad jie neveikia. Idealiausia tokiu atveju būtų PR'as, arba bent patvirtinimas, kad štai, ta naujausia versija irgi neveikia.

Dėl balandžio mėn. klausimo. Projektas šiuo metu faktiškai yra „maintenance“ stadijoje. Jam tiesiog skiriama labai mažai dėmesio, ir labai gali būti, kad jūsų klausimų tiesiog niekas nepamatė (pvz., aš juos pamačiau tik dabar – reikės užsiprenumeruoti, kad ateity matyčiau iškart).

**Comment by lifebarier** [comment]
As suprantu kad zmones tur asmeinini gyvenima ir ribota laika ...
Bet cia as sakyciau gan svarbus projektas. Ir jis taip smarkiai apleistas kad, sorry to say, - it's dead. Koks "maintenance" kai paprastas zmogus isirases libreofice bus pasitiktas neveikiancio spellchecko... nuo 2013...

**Comment by rimas-kudelis** [comment]
„Paprastas žmogus“ paprastai gauna spellchecką kartu su „LibreOffice“, nereikia jam to paketo atskirai siųstis. Ar norite pasakyti, kad ir „gamyklinis“ lietuviškas spellcheckas „LibreOffice“ neveikia?

Ir sakau – visiškai neaišku, kaip atnaujinti tą žodyną „LibreOffice“ svetainėje. Aš jokių loginų ne(be)turiu, o ir motyvacijos neypač. Va „Mozilloje“ turiu prisijungimus, pagalvojau, įkelsiu 1.3.2 ta proga, bet ne! Pasirodo, reikalaujama papildinio struktūra pasikeitė. Seniau įkelta versija buvo automatiškai pakonvertuota, o štai dabar „senamadiško“ failo įkelti jau nebegaliu.

Na, bet Mozilla čia offtopikas truputį.
Vat dabar tik pamačiau, kad naudojate „Linux“. Tai jūsų atveju tuo labiau neverta siųstis šito extensiono atskirai „Lbreoffice'ui“ – vietoj to tiesiog įsidiekite hunspell-lt paketą.

O dėl projekto svarbos tai žinokit papildomos rankos visada priimamos. :)

**Comment by rimas-kudelis** [comment]
Pamėginsiu atkurti savo paskyrą ir atnaujinti tą „LibreOffice“ priedą.

**Comment by lifebarier** [comment]
> nereikia jam to paketo atskirai siųstis.

By default libreoffice bent man neateina su LT spellcheckeriu (pirmakarta uzsiroviau ant sito keli metai atgal ant xubuntu, dabar manjaro, tai manau ne distro beda). Ji tenka siustis is libres extension managerio ar kaip ten vadinasi. Nebent aisku as akzka smarkiai netaip darau.

> įsidiekite hunspell-lt

Isirasau libre kaip paprastas useris, noriu spellchecko, pamaigau per optionus, randu extension manageri, atsisiunciu spellchecka, neveikia. Kaip simple useris as nesitikiu kad man kazka reikia atskirai irasinet kai "yra" spellcheckas writeryje.

O tai ant windowsu spellcheckas atsiustas per libre veikia?

> papildomos rankos visada priimamos

No offense, bet pamates tokia beda nuo 2013 as buciau labiau linkes forkint o ne padet (velgi, as pats neturiu perdaug laisvo laiko rankose ir suprantu kad kiti netur. Ypac kai panasu jog mazai kas uzsirauna ant sitos bedos)

**Comment by rimas-kudelis** [comment]
> > nereikia jam to paketo atskirai siųstis.
> 
> By default libreoffice bent man neateina su LT spellcheckeriu (pirmakarta uzsiroviau ant sito keli metai atgal ant xubuntu, dabar manjaro, tai manau ne distro beda). Ji tenka siustis is libres extension managerio ar kaip ten vadinasi. Nebent aisku as akzka smarkiai netaip darau.
>
> > įsidiekite hunspell-lt
> 
> Isirasau libre kaip paprastas useris, noriu spellchecko, pamaigau per optionus, randu extension manageri, atsisiunciu spellchecka, neveikia. Kaip simple useris as nesitikiu kad man kazka reikia atskirai irasinet kai "yra" spellcheckas writeryje.

Ai, na čia mano prielaidos, kad linuxistai viską, ką įmanoma, instaliuojasi iš distribucijos paketų. Gal per daug projektuoju save patį. :) Suprantu, kad ne kiekvienas taip daro.

O „by default“ tai čia taikiau labiau „Windows“ naudotojams, kurie parsisiunčia Windows installerį ir ten suklikina next-next-next-finish. Tai bent jau jei instaliuojasi lietuviškoje „Windows“ aplinkoje, manau, jog jiems iškart ir kalbos paketas pasiūlomas, ir rašybos žodynai. Nors, tiesą sakant, nesu tuo tikras, nes jau senokai neteko per tą procesą eiti.

Įdiegus „hunspell-lt“ paketą „Manjaro“ priemonėmis, tie žodynai veiktų ne tik su „LibreOffice“, bet ir su kitomis programomis, kurios juos palaiko, dėl to ir siūliau taip. Bet aišku, tai nesprendžia problemos, kad aštuonerius metus platinom (aš platinau) neveikiantį papildinį per LibO svetainę.

> O tai ant windowsu spellcheckas atsiustas per libre veikia?

Tikriausiai ne, dėl tos pačios priežasties, kaip ir ant „Linux“.

> > papildomos rankos visada priimamos
> 
> No offense, bet pamates tokia beda nuo 2013 as buciau labiau linkes forkint o ne padet (velgi, as pats neturiu perdaug laisvo laiko rankose ir suprantu kad kiti netur. Ypac kai panasu jog mazai kas uzsirauna ant sitos bedos)

Čia jau asmeniniai pasirinkimai. Aš dažniausiai jei ką nors ir nuforkinu su tikslu pataisyti, tai bent jau PR su savo pataisomis padarau. Aišku, kartais tas PR'as gal lieka kaboti amžiams, bet, jei nėra planų kažką ten iš pagrindų imti, keisti ir maintaininti, forkas dėl forko dažniausiai ir liks tiesiog forku su vos viena-kita pataisa. Kita vertus, jei forkas daromas su mintimi maintaininti, tai kam tas forkas, jei pagrindinis projektas savanorius priima ir nėra kaip nors ten etiškai ar kitaip nepriimtinas. :) Na, manau supratote, ką turiu omeny.

O šiaip, no offence taken. Ir jau įkėliau 1.3.2 versiją į extensions.libreoffice.org. Tik dar neišsiaiškinau, kaip jos būseną iš „Draft“ pakeisti į „Published“, tad kol kas viešai matoma vis dar 1.3.

**Comment by rimas-kudelis** [comment]
@lifebarier [žodynas atnaujintas](https://extensions.libreoffice.org/en/extensions/show/lithuanian-spellcheck-and-hyphenation-dictionaries).

Tuo pačiu įkėliau ir [„Semantikos“ rašybos tikrinimo žodyną](https://extensions.libreoffice.org/en/extensions/show/5752), tad dabar galima rinktis iš dviejų variantų.

Gal patikrintumėte, ar dabar ispell-lt žodynas jums veikia? Jei veikia, galėtume uždaryti šitą bugą.

**Comment by lifebarier** [comment]
@rimas-kudelis dekui, veikia. 
Kas biski idomu kad libre office "Check for updates" ant extensiono aiskino kad updeitu nera, bet nuejus per "Get more extensions online..." matosi 1.3.2 versija, bet cia jau venias zino kieno darzas.

**Comment by alga** [comment]
Wow, ačiū, Rimai!
